TXT_DISABLED   = "/VYP/"
TXT_ESC_isExit = "ESC - Ukončit"
TXT_SEL_INFO   = "Stiskněte další klávesu pro výběr: {c}\n (nebo stiskněte ENTER pro potvrzení, nebo BACKSPACE pro odstranění posledního znaku)"
TXT_INVALID_TYPE_IN_LIS = "Neplatný typ v seznamu"
TXT_RPT_CHCS  = "Opakovaná volba"
TXT_ERR       = "CHYBA"
TXT_NFO       = "Info"
TXT_PRESS_KEY = "Stiskněte klávesu pro výběr ..."
TXT_SELECT    = "Vyberte: {c}"
TXT_BACK      = "Zpět"
TXT_QUIT      = "Ukončit"
TXT_ABORTED   = "Přerušeno"
TXT_CMENU_ERR01 = "Chyba skriptu, počet vlevo a vpravo nesouhlasí"
TXT_CMENU_ERR02 = "Chyba skriptu, očekává se tuple"
TXT_CMENU_ERR03 = "Chyba skriptu, nesprávně nastavený spaceBetweenTexts: {tx}"
TXT_INPUT_A     = "Vstup"
TXT_INPUT_NEW_PWD = "Nové heslo"
TXT_END         = "Konec"

TXT_HLPR_STATUS_RUNNING = "SPUŠTĚNO"
TXT_HLPR_STATUS_STPDIS = "ZASTAVENO A VYPNUTO"
TXT_HLPR_STATUS_STPENA = "ZASTAVENO A POVOLENO"
TXT_HLPR_STATUS_NM_EMP = "Název služby je prázdný"
TXT_HLPR_STATUS_ERR="Chyba při získávání stavu služby"
TXT_HLPR_MUST_BE_ROOT="Tento skript musí být spuštěn jako root."

TXT_INPUT_ERR = "Vstup je příliš krátký, min 1 znak"
TXT_LEN_ERR = "Vstup je příliš dlouhý, max {maxLen} znaků"

TXT_INPUT_YES = "Ano"
TXT_INPUT_NO = "Ne"
TXT_INPUT_RETURNKEY = "Stiskněte ENTER pro pokračování ..."
TXT_INPUT_ANYKEY = "Stiskněte libovolnou klávesu pro pokračování ..."
TXT_INPUT_USERNAME = "Zadejte uživatelské jméno: "
TXT_INPUT_PWD = "Zadejte heslo"
TXT_INPUT_PWD_AGAIN = "ZNOVU pro potvrzení"
TXT_INPUT_PORT = "Zadejte port"
TXT_SSMD_PORT_REANGE = "10000-65000"

TXT_C_UNIT_servNameType = "Neplatný typ parametru 'service_name'."
TXT_C_UNIT_servUnitType = "Typ jednotky služby nesouhlasí."
TXT_C_UNIT_servDotErr = "Název služby může obsahovat maximálně jednu tečku."
TXT_C_UNIT_servAtErr = "Název služby nesmí obsahovat '@'; šablona je specifikována parametrem."
TXT_C_UNIT_servTmplNameErr = "Název šablony nesmí obsahovat '@' nebo tečku."

TXT_C_UNIT_badCStatus = "Parametr status musí být instance c_unit_status"

TXT_SSMD_ERR01 = "Vstupní řetězec je prázdný. Očekávaný formát je např. '100ms', '1m 30sec'."
TXT_SSMD_ERR02 = "Neplatná část vstupu: '{tx}'. Očekávaný formát je např. '100ms'."
TXT_SSMD_ERR03 = "Neznámá jednotka: '{tx}'."
TXT_SSMD_ERR04 = "Čas musí být nezáporné číslo."
TXT_SSMD_ERR05 = "Neplatný typ klíče '{tx}'"
TXT_SSMD_ERR06 = "Neplatný typ hodnoty pro klíč '{tx}'"
TXT_SSMD_ERR07 = "Není specifikován zdrojový soubor"
TXT_SSMD_ERR08 = "Soubor služby již existuje"
TXT_SSMD_ERR09 = "Zdrojový soubor neexistuje"
TXT_SSMD_ERR10 = "Zdrojový soubor chybí"
TXT_SSMD_ERR11 = "Nepodařilo se vytvořit službu"
TXT_SSMD_ERR12 = "Soubor služby neexistuje"
TXT_SSMD_ERR13 = "Nepodařilo se odstranit službu"
TXT_SSMD_ERR14 = "Nepodařilo se zastavit službu"
TXT_SSMD_ERR15 = "Chyba při zápisu do souboru služby"
TXT_SSMD_ERR16 = "Chyba při zápisu do souboru časovače"
TXT_SSMD_ERR17 = "Neplatné uživatelské jméno, jsou povoleny pouze písmena, číslice, podtržítka a pomlčky"
TXT_SSMD_ERR18 = "Neplatný vstup"
TXT_SSMD_ERR19 = "!!! Neplatné heslo\nHeslo musí obsahovat alespoň 8 znaků, včetně písmen, číslic a speciálních znaků"
TXT_SSMD_ERR20 = "Hesla se neshodují. Zkuste to znovu."
TXT_SSMD_ERR21 = "Neplatný port. Musí být mezi 10000-65000"

TXT_STATUS_ENA = "POVOLENO"
TXT_STATUS_DIS = "VYPNUTO"
TXT_STATUS_RUN = "SPUŠTĚNO"
TXT_STATUS_STP = "ZASTAVENO"
TXT_STATUS_NEX = "NEEXISTUJE"

TXT_C_UNIT_noSystemd = "Na tomto systému není 'Systemd' k dispozici."

TXT_SELECT_TITLE = "Vyberte z možností"

TXT_UART_ERR_LEN_MIN = "[ERROR] Délka musí být větší než 0."
TXT_UART_ERR_LEN_MAX = "[ERROR] Délka je příliš velká (max 1024)."
TXT_UART_ERR_REPEAT_MIN = "[ERROR] Počet opakování musí být větší než 0."
TXT_UART_ERR_REPEAT_MAX = "[ERROR] Počet opakování je příliš velký (max 100)."
TXT_UART_OK_HASH_CONTENT = "Hash i obsah odpovídá."
TXT_UART_FAIL_HASH_CONTENT = "Hash OK - CHYBA obsahu."
TXT_UART_FAIL_HASH = "Hash CHYBA {received_hash} != {computed_hash}"
TXT_UART_FAIL_INVALID_RESPONSE = "Neplatný formát odpovědi: {line}"
TXT_UART_TIMEOUT = "Nebyla přijata žádná odpověď."
TXT_UART_ERR_MISSING_PYSERIAL = "[ERROR] Chybí knihovna pyserial. Nainstaluj ji příkazem: pip install pyserial"
TXT_UART_ERR_OPEN_PORT = "[ERROR] Nelze otevřít port {port}: {err}"
TXT_UART_SEND_STATUS = "[SEND {attempt}] bajtů: {length} (hash: {hash})"
TXT_UART_RECEIVER_TITLE = "[INFO] Serial tester - Receiver {version} by dvestezar.cz"
TXT_UART_INFO_PORT = "[INFO] Port: {port} @ {baudrate} baud"
TXT_UART_RECEIVER_ACTIVE = "[RECEIVER] Režim příjmu aktivní. Čekám na zprávy..."
TXT_UART_RECEIVER_EXIT_HINT = "[RECEIVER] Ukonči pomocí Ctrl+C"
TXT_UART_RECEIVER_STOPPED = "[RECEIVER] Ukončeno uživatelem."
TXT_UART_IN_BYTES_RECEIVED = "[IN ] přijato bajtů: {length}"
TXT_UART_OUT_BYTES_SENT = "[OUT] odesláno bajtů: {length}, hash: {hash}"
TXT_UART_SENDER_TITLE = "********** Serial tester - Sender {version} by dvestezar.cz **********"
TXT_UART_HEADER_CMD_HINT = "Zadej příkaz 'test[<len>][n<repeat>]' nebo 'exit'."
TXT_UART_HEADER_HELP_HINT = "Pro nápovědu zadej 'help'."
TXT_UART_HEADER_RCV_HINT = "Pro spuštění režimu příjmu zadej 'rcv'."
TXT_UART_HELP_TITLE = "\n*** Dostupné příkazy: ***"
TXT_UART_HELP_SYNTAX = "  test              → syntaxe = test[<len>][n<repeat>]"
TXT_UART_HELP_TEST_DEFAULT = "  - test              → odešle 64 znaků (defaultní test)"
TXT_UART_HELP_TEST_LEN = "  - test120           → odešle 120 znaků"
TXT_UART_HELP_TEST_REPEAT = "  - test80n5          → odešle 80 znaků, opakuje 5x"
TXT_UART_HELP_TEST_REPEAT_DEFAULT = "  - testn3            → odešle 64 znaků, opakuje 3x"
TXT_UART_HELP_RCV = "  rcv               → spustí režim příjmu"
TXT_UART_HELP_CLS = "  cls               → smaže obrazovku"
TXT_UART_HELP_EXIT = "  exit              → ukončí skript"
TXT_UART_HELP_HELP = "  help              → zobrazí tento přehled\n"
TXT_UART_SWITCH_TO_RCV = "--- >>> Spouštím režim příjmu..."
TXT_UART_BACK_TO_TX = "--- <<< Návrat do odesílacího režimu."
TXT_UART_SENDING_TEST = "[INFO] Odesílám testovací zprávy ({length} znaků, {repeat}x)..."
TXT_UART_PRESS_ENTER = "Pro pokračování stiskněte ENTER..."
TXT_UART_STOPPED_BY_USER = "\n[INFO] Ukončeno uživatelem."
TXT_UART_ERR_OCCURRED = "[ERROR] Došlo k chybě: {err}"
TXT_UART_ERR_CLOSE_PORT = "[ERROR] Nelze zavřít port: {err}"
TXT_UART_ARG_DESCRIPTION = "Odesílá testovací zprávy na sériový port a ověřuje odpovědi."
TXT_UART_ARG_PORT_HELP = "Sériový port, např. /dev/ttyS3"
TXT_UART_ARG_BAUDRATE_HELP = "Rychlost v baudech (default: {baudrate})"
TXT_UART_ARG_RECEIVER_HELP = "Spustit jako receiver (příjemce zpráv)"
TXT_UART_EXITING = "Ukončuji."
